Repository MewsSystems/gitbook-connector-api, pull requests merged in 2020-03, with the labels that each got.

#134 Updates accounting items definition
  operations/finance.md
  operations/reservations.md
Labels: Deployed, Documentation

#133 Past price updates not allowed
  operations/services.md
Labels: Deployed, Documentation

#132 New time filter format for bills/getAll
  operations/finance.md
Labels: Documentation, Time filters

#126 Removed SpaceCategories extent default
  operations/enterprises.md
Labels: Deployed, Documentation

#125 Allow Enquired in reservation/add
  operations/reservations.md
Labels: Deployed, Documentation

#112 Add geo location to configuration/get response
  operations/configuration.md
  operations/customers.md
  operations/enterprises.md
Labels: Deployed, Documentation

#114 Companies/add
  operations/enterprises.md
Labels: Deployed, Documentation

#115 Companies/update
  operations/enterprises.md
Labels: Deployed, Documentation

#129 New time filters cashierTransactions/getAll
  operations/finance.md
Labels: Documentation, Time filters

#131 New time filters outletItems/getAll
  operations/finance.md
Labels: Documentation, Time filters

#130 New time filter format for restrictions/getAll
  operations/services.md
Labels: Documentation, Time filters

#121 New time filters spaceBlocks/getAll
  operations/enterprises.md
Labels: Deployed, Documentation, Time filters

#119 New operation tasks/getall
  operations/README.md
  operations/enterprises.md
Labels: Deployed, Documentation, Time filters

#110 customers/getAll consolidation
  operations/README.md
  operations/customers.md
Labels: Documentation, Time filters

#135 Webhooks fix
  webhooks.md
Labels: Documentation

#137 Extent is required
  operations/customers.md
  operations/enterprises.md
  operations/finance.md
  operations/reservations.md
  operations/services.md
Labels: Documentation
