Repository MewsSystems/gitbook-connector-api, pull requests merged in 2024-06, with the labels that each got.

#599 Added SendEmail to cancel reservation
  changelog/README.md
  operations/reservations.md
Labels: Documentation

#604 New section Concepts and Time units
  README.md
  SUMMARY.md
  changelog/README.md
  changelog/changelog2022.md
  concepts/README.md
  concepts/time-units.md
  getting-started/README.md
  guidelines/README.md
  operations/availabilityadjustments.md
  operations/availabilityblocks.md
  operations/products.md
  operations/rates.md
Labels: Documentation

#600 Generator improvements: Relative links, sorting
  _generator/index.js
  _generator/jsonschema.js
  _generator/page.js
  _generator/schema.js
  _generator/sorting/operationSort.js
  _generator/sorting/propertySort.js
  _generator/sorting/schemaSort.js
  _generator/types.d.ts
  _generator/utils.js
  operations/accountnotes.md
  operations/countries.md
  operations/devices.md
  operations/orderitems.md
  operations/services.md
Labels: Documentation, Generator

#603 Migrate services to autogenerated docs 2
  _generator/config.yaml
  _generator/overrides.yaml
  _generator/page.js
  _generator/schema.js
  _generator/templates/deprecatedProperty.edge
  _generator/templates/parameters.edge
  _generator/templates/property.edge
  _generator/templates/resource.edge
  operations/services.md
Labels: Generator

#605 Introduce types map
  _generator/collect-schemas.js
  _generator/index.js
  _generator/jsonschema.js
  _generator/overrides.yaml
  _generator/page.js
  _generator/template-schema.js
  _generator/types-resolver.js
  _generator/types.d.ts
  _generator/types.yaml
  _generator/utils.js
  operations/_objects.md
  operations/accountnotes.md
  operations/countries.md
  operations/currencies.md
  operations/devices.md
  operations/exchangerates.md
  operations/images.md
  operations/orderitems.md
  operations/services.md
Labels: Generator

#606 moved Taxation page to Concepts
  SUMMARY.md
  changelog/README.md
  concepts/README.md
  concepts/taxation.md
  guidelines/README.md
Labels: Documentation

#607 CON-2240: Sort reservations documentation (no changes)
  operations/reservations.md
Labels: Generator

#609 Expose deprecationMessage in reference docs
  _generator/.editorconfig
  _generator/jsonschema.js
  _generator/page.js
  _generator/template-schema.js
  _generator/templates/deprecatedProperty.edge
  _generator/templates/resource.edge
  _generator/types.d.ts
  operations/services.md
Labels: Generator

#568 Restriction splicing - remove restricted
  changelog/README.md
  operations/README.md
  operations/restrictions.md
Labels: Documentation

#608 CON-2240: Migrate reservations to docs generator
  _generator/config.yaml
  _generator/sorting/operationSort.js
  _generator/types.yaml
  operations/_objects.md
  operations/reservations.md
Labels: Generator

#614 Moved restrictions content from API Operations to Concepts
  SUMMARY.md
  changelog/README.md
  concepts/README.md
  concepts/restrictions.md
  operations/restrictions.md
  use-cases/revenue-management.md
Labels: Documentation

#616 Small tweaks to Common objects
  operations/_objects.md
Labels: Documentation
