Repository MewsSystems/gitbook-connector-api, pull requests merged in 2024-12, with the labels that each got.

#694 Add "Set rates" operation
  _generator/types.yaml
  changelog/README.md
  operations/README.md
  operations/rates.md
Labels: con.connectivity

#698 Routing rule - AssignmentTargetType documentation
  changelog/README.md
  operations/routingrules.md
Labels: Documentation

#697 CON-4914: Update Documentation for availabilityBlocks/getAll Endpoint…
  changelog/README.md
  operations/availabilityblocks.md
Labels: Documentation

#693 CON-2232: Migrate payments to docs generator
  _generator/config.yaml
  _generator/types.yaml
  changelog/README.md
  operations/_objects.md
  operations/orders.md
  operations/outletbills.md
  operations/payments.md
  operations/rates.md
  operations/reservations.md
Labels: Generator

#692 Documentation changes towards a neater, unified structure (2)
  .gitbook.yaml
  README.md
  SUMMARY.md
  changelog/README.md
  changelog/changelog2017.md
  changelog/changelog2018.md
  changelog/changelog2019.md
  changelog/changelog2020.md
  changelog/changelog2021.md
  changelog/changelog2022.md
  concepts/README.md
  deprecations/README.md
  events/README.md
  events/communicate.md
  events/websockets.md
  events/wh-faq.md
  events/wh-general.md
  events/wh-integration.md
  guidelines/README.md
  guidelines/best-practices.md
  guidelines/responses.md
  use-cases/customer-management.md
  use-cases/device-integration.md
  use-cases/events.md
  use-cases/guest-technology.md
  use-cases/housekeeping.md
  use-cases/how-to.md
  use-cases/messaging.md
  use-cases/mews-terminals.md
  use-cases/reputation-management.md
  use-cases/revenue-management.md
  webhooks/README.md
Labels: Documentation

#700 Extended identity document with doc support nr
  changelog/README.md
  operations/customers.md
Labels: Documentation, con.connectivity

#701 Add hybrid identifier for "Update rate price"
  _generator/types.yaml
  changelog/README.md
  operations/rates.md
Labels: con.connectivity

#699 Identity documents endpoints
  SUMMARY.md
  _generator/config.yaml
  _generator/types.yaml
  changelog/README.md
  operations/README.md
  operations/identitydocuments.md
Labels: Documentation, Generator

#696 CON-4824 Update the documentation for bills/update endpoint
  _generator/types.yaml
  changelog/README.md
  operations/README.md
  operations/bills.md
Labels: Documentation

#702 CON-4203: Improve + fix Title enum docs
  _generator/template-schema.js
  operations/accounts.md
  operations/bills.md
  operations/customers.md
Labels: Generator

#703 Improved `payments/refund` description in docs
  changelog/README.md
  operations/payments.md
Labels: Documentation, Generator
