Repository MewsSystems/gitbook-connector-api, pull requests merged in 2024-11, with the labels that each got.

#669 Con-4165:Add "Bill Name" to bills/getAll response documentation
  changelog/README.md
  operations/bills.md
Labels: con.connectivity

#670 MMP-8076: Added GroupNames to Enterprise
  changelog/README.md
  operations/configuration.md
  operations/enterprises.md
Labels: Generator

#672 Regenerate docs
  changelog/README.md
  operations/accountingcategories.md
  operations/accountnotes.md
  operations/accounts.md
  operations/agecategories.md
  operations/availabilityadjustments.md
  operations/bills.md
  operations/cancellationpolicies.md
  operations/orderitems.md
  operations/outletitems.md
  operations/products.md
  operations/rategroups.md
  operations/reservations.md
  operations/resourcecategories.md
  operations/restrictions.md
  operations/services.md
  operations/tasks.md
  operations/vouchercodes.md
  operations/vouchers.md
Labels: Generator

#671 generator: Update dependencies
  _generator/package-lock.json
  _generator/package.json
Labels: Generator

#675 Regenerate reservation docs
  operations/reservations.md
Labels: Generator

#680 Business segments auto generated
  _generator/config.yaml
  _generator/types.yaml
  operations/businesssegments.md
Labels: Generator

#684 Fix description
  operations/businesssegments.md
Labels: Generator

#685 Regenerated business segments
  operations/businesssegments.md
Labels: Generator

#677 CON-2214: Generate Customers docs
  _generator/config.yaml
  _generator/types.yaml
  changelog/README.md
  deprecations/README.md
  operations/README.md
  operations/customers.md
Labels: Generator

#678 Regenerate enterprises and configuration
  _generator/config.yaml
  _generator/types.yaml
  changelog/README.md
  operations/configuration.md
  operations/enterprises.md
Labels: Generator

#683 Add service overbooking limits docs
  SUMMARY.md
  _generator/config.yaml
  _generator/types.yaml
  changelog/README.md
  operations/README.md
  operations/serviceoverbookinglimits.md
Labels: Generator

#686 Increased AssignedRateIds to 10
  _generator/types.yaml
  changelog/README.md
  operations/vouchers.md
Labels: Documentation

#687 Improve sorting + regenerate docs
  _generator/sorting/operationSort.js
  operations/accounts.md
  operations/bills.md
  operations/cancellationpolicies.md
  operations/customers.md
  operations/reservations.md
Labels: Generator

#689 Add AvailabilityBlockNumber
  changelog/README.md
  operations/availabilityblocks.md
Labels: Documentation

#691 Added "Update products pricing" and "Delete rates" operations
  _generator/types.yaml
  changelog/README.md
  operations/README.md
  operations/products.md
  operations/rates.md
Labels: con.connectivity
