Repository MewsSystems/gitbook-connector-api, pull requests merged in 2024-07, with the labels that each got.

#621 CON-2197-Migrate-Availability-Adjustments-vol2
  _generator/types.yaml
  operations/availabilityadjustments.md
Labels: Generator

#622 CON-2256 Migrate Vouchers
  _generator/config.yaml
  _generator/types.yaml
  operations/vouchers.md
Labels: Generator

#617 Invoice payment type
  changelog/README.md
  operations/payments.md
Labels: con.connectivity

#587 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: con.connectivity

#612 correct cancelled to canceled in Use Cases
  use-cases/events.md
  use-cases/mews-terminals.md
  use-cases/point-of-sale.md
Labels: Documentation, con.connectivity
