Repository MewsSystems/gitbook-connector-api, pull requests merged in 2025-07, with the labels that each got.

#782 RequestId header and in response
  changelog/README.md
  guidelines/responses.md
Labels: Documentation

#783 CON-7483: Generate docs for polymorphic requests
  _generator/collect-jsonschema.js
  _generator/collect-schemas.js
  _generator/index.js
  _generator/jsonschema.js
  _generator/page.js
  _generator/template-schema.js
  _generator/templates/parameters.edge
  _generator/types.d.ts
  _generator/types.yaml
  operations/commands.md
Labels: Generator

#799 CON-8032 Update changelog
  changelog/README.md
Labels: con.connectivity
