Repository MewsSystems/gitbook-connector-api, pull requests merged in 2025-01, with the labels that each got.

#706 Migrating Cashiers
  _generator/config.yaml
  operations/cashiers.md
Labels: Generator, con.connectivity

#704 Documentation changes towards a neater, unified structure (3)
  .gitbook.yaml
  SUMMARY.md
  changelog/README.md
  changelog/changelog2024.md
  concepts/README.md
  concepts/multi-property.md
  guidelines/README.md
  guidelines/authentication.md
  guidelines/environments.md
  guidelines/requests.md
  operations/accountingitems.md
  operations/addresses.md
  operations/availabilityblocks.md
  operations/cashiertransactions.md
  operations/commands.md
  operations/companionships.md
  operations/companycontracts.md
  operations/counters.md
  operations/creditcards.md
  operations/departments.md
  operations/loyaltymemberships.md
  operations/loyaltyprograms.md
  operations/loyaltytiers.md
  operations/messages.md
  operations/messagethreads.md
  operations/orders.md
  operations/paymentrequests.md
  operations/productcategories.md
  operations/productserviceorders.md
  operations/reservationgroups.md
  operations/resourceaccesstokens.md
  operations/resourceblocks.md
  operations/resources.md
  operations/routingrules.md
  operations/rules.md
  operations/serviceordernotes.md
Labels: Documentation

#705 Clarified definition of 'discontinued'
  changelog/README.md
  deprecations/README.md
Labels: Documentation

#653 Migrate Addresses
  _generator/config.yaml
  _generator/types.yaml
  operations/addresses.md
Labels: Generator, con.connectivity

#708 Added availabilityBlock filtering to reservations/getAll/2023-06-06
  changelog/README.md
  operations/reservations.md
Labels: Generator, con.connectivity

#709 Service Order Notes - Generator
  _generator/config.yaml
  _generator/types.yaml
  operations/serviceordernotes.md
Labels: Generator

#710 Add PaymentUpdated webhook
  changelog/README.md
  events/wh-general.md
Labels: Documentation

#711 Regenerate all docs
  _generator/types.yaml
  operations/accountingcategories.md
  operations/accountnotes.md
  operations/accounts.md
  operations/addresses.md
  operations/agecategories.md
  operations/availabilityadjustments.md
  operations/bills.md
  operations/businesssegments.md
  operations/cancellationpolicies.md
  operations/cashiers.md
  operations/companies.md
  operations/configuration.md
  operations/customers.md
  operations/enterprises.md
  operations/exports.md
  operations/identitydocuments.md
  operations/orderitems.md
  operations/outletitems.md
  operations/payments.md
  operations/products.md
  operations/rategroups.md
  operations/rates.md
  operations/reservations.md
  operations/restrictions.md
  operations/serviceordernotes.md
  operations/serviceoverbookinglimits.md
  operations/services.md
  operations/sourceassignments.md
  operations/vouchercodes.md
  operations/vouchers.md
Labels: Documentation, Generator

#720 CON-5228 add documentation for cancel order items endpoint
  changelog/README.md
  operations/orderitems.md
Labels: Generator

#714 Generator - Availability blocks
  _generator/types.yaml
  changelog/README.md
  deprecations/README.md
  operations/availabilityblocks.md
Labels: Generator

#721 Fix changelog
  changelog/README.md
Labels: Documentation

#722 Fixed two broken links
  events/wh-faq.md
Labels: Documentation

#723 Remove restricted from operations table
  operations/README.md
Labels: Documentation

#718 Update deprecation text for reservations
  operations/reservations.md
Labels: Documentation

#717 Add AccountIds filtering for payments/getAll
  changelog/README.md
  operations/payments.md
Labels: Documentation

#715 Added Value for resourceAccessTokens/update
  changelog/README.md
  operations/resourceaccesstokens.md
Labels: Documentation

#713 Address for enterprises/getAll and removed deprecation
  changelog/README.md
  deprecations/README.md
  operations/configuration.md
  operations/enterprises.md
Labels: Documentation, con.connectivity

#712 Documents deprecation
  changelog/README.md
  deprecations/README.md
  operations/customers.md
Labels: Documentation
