Repository MewsSystems/gitbook-connector-api, pull requests merged in 2025-05, with the labels that each got.

#761 Updated all 2025 and 2024 changelog entries to the current format.
  changelog/README.md
  changelog/changelog2024.md
Labels: Documentation

#762 Added clarification to Scope of restrictions.
  changelog/README.md
  concepts/restrictions.md
Labels: Documentation

#764 CON-5797: Improve examples for bill company data
  operations/bills.md
Labels: con.connectivity

#763 CON-7106: Expose IsDefault in rates/getAll
  changelog/README.md
  operations/rates.md
Labels: con.connectivity

#767 CreatorProfileId and UpdaterProfileId added
  _generator/package-lock.json
  changelog/README.md
  operations/customers.md
Labels: Documentation, Generator
