Repository MewsSystems/gitbook-connector-api, pull requests merged in 2025-02, with the labels that each got.

#733 CON-5700 add API documentation for creditCards/disable endpoint
  changelog/README.md
  operations/payments.md
Labels: Documentation, Generator

#736 Con 5226 make company contracts delete multiproperty
  changelog/README.md
  operations/companycontracts.md
Labels: Generator

#737 CON-5791 Add documentation for reservations/getChannelManagerDetails end point
  changelog/README.md
  operations/README.md
  operations/reservations.md
Labels: Documentation, Generator, con.connectivity

#740 CON-5841 Generate documentation for ActualEndUtc filter in reservations/getAll ver 2023-06-06
  changelog/README.md
  operations/reservations.md
Labels: Generator, con.connectivity

#739 CON-5778 Sex Field in Customers/update should be marked as Optional
  changelog/README.md
  operations/customers.md
Labels: Documentation, con.connectivity
